const $=s=>document.querySelector(s);const hospitals=['Lagos State University Hospital','University of Nigeria Teaching Hospital','National Hospital Abuja','Enugu State University Hospital','University College Hospital'];
const distributions=[[34,30,24,25],[8,9,6,13],[24,31,8,19],[17,19,24,20],[29,28,25,24]];let timer=null,round=0,ready=false,file=null;
function renderNetwork(){const count=+$(`#hospitalSlider`).value;$(`#hospitalCount`).value=count;$(`#hospitals`).innerHTML=hospitals.slice(0,count).map((h,i)=>`<div class="hospital" data-i="${i}"><i>â™Ÿ</i>${h}</div>`).join('');$(`#bars`).innerHTML=distributions.slice(0,count).map((d,i)=>`<div class="bar-wrap"><div class="bar" style="--h:${55+Math.max(...d)}px"><i class="covid-bg" style="--v:${d[3]}"></i><i class="tb-bg" style="--v:${d[2]}"></i><i class="pneumonia-bg" style="--v:${d[1]}"></i><i class="normal-bg" style="--v:${d[0]}"></i></div><div class="bar-label">H${i+1}</div></div>`).join('');$(`#nodesStatus`).textContent=`${round?count:0}/${count}`}
function log(text,type=''){const t=new Date().toLocaleTimeString('en-GB');$(`#terminalLog`).insertAdjacentHTML('beforeend',`<div class="log ${type}"><time>[${t}]</time>${text}</div>`);$(`#terminalLog`).scrollTop=99999}
function unlock(){ready=true;$(`#lockedOverlay`).classList.add('hidden');$(`#modelBadge`).className='pill ready';$(`#modelBadge`).textContent='â— MobileViT Ready';$(`#trainBtn`).disabled=false;$(`#trainBtn`).textContent='â–¶  Initialize Training';$(`#syncStatus`).textContent='Training Complete';$(`#nodesStatus`).textContent=`0/${$(`#hospitalSlider`).value}`;log('Federated MobileViT training successfully completed.','success');log('Clinical interface unlocked for inference.','success')}
function train(){if(timer)return;round=0;$(`#trainBtn`).disabled=true;$(`#syncStatus`).textContent='Pre-processing';['Loading Nigeria Chest X-ray Dataset...','Resizing images to 256 Ã— 256...','Applying CLAHE contrast enhancement...','Applying intensity normalization...','Performing data augmentation for robustness...','Pre-processing complete. Initializing FL framework...'].forEach((x,i)=>setTimeout(()=>log(x,i===5?'success':''),i*180));setTimeout(()=>{document.querySelectorAll('.hospital').forEach(x=>x.classList.add('active'));$(`#syncStatus`).textContent='Local Training';timer=setInterval(()=>{round++;$(`#roundStatus`).textContent=`${round}/50`;renderNetwork();log(`Round ${round} completed. Global model updated.`);if(round===50){clearInterval(timer);timer=null;unlock()}},120)},1200)}
function reset(){clearInterval(timer);timer=null;round=0;ready=false;file=null;$(`#roundStatus`).textContent='0/50';$(`#syncStatus`).textContent='Idle';$(`#lockedOverlay`).classList.remove('hidden');$(`#modelBadge`).className='pill locked';$(`#modelBadge`).textContent='â–£ Awaiting Global Model';$(`#terminalLog`).innerHTML='';$(`#preview`).removeAttribute('src');$(`#inputPlaceholder`).classList.remove('hidden');$(`#attentionCanvas`).classList.add('hidden');$(`#attentionPlaceholder`).classList.remove('hidden');$(`#result`).classList.add('hidden');$(`#diagnoseBtn`).disabled=true;$(`#trainBtn`).disabled=false;renderNetwork();log('System environment reset.','warn')}
function choose(f){if(!f)return;file=f;const reader=new FileReader();reader.onload=e=>{$(`#preview`).src=e.target.result;$(`#inputPlaceholder`).classList.add('hidden')};reader.readAsDataURL(f);$(`#diagnoseBtn`).disabled=!ready}
async function diagnose(){if(!file||!ready)return;const btn=$(`#diagnoseBtn`);btn.disabled=true;btn.textContent='Analyzingâ€¦';const body=new FormData();body.append('file',file);try{const res=await fetch('/api/predict',{method:'POST',body});if(!res.ok)throw new Error(await res.text());const data=await res.json();showResult(data);drawAttention(data.attention_map)}catch(e){log(`Diagnostic service error: ${e.message}`,'warn');$(`#result`).classList.remove('hidden');$(`#result`).innerHTML='<b>Model service unavailable.</b> Start server.py and retry.'}finally{btn.disabled=false;btn.textContent='ÏŸ  Run Diagnostics'}}
function showResult(d){$(`#result`).classList.remove('hidden');const probs=Object.entries(d.probabilities).map(([k,v])=>`${k}: ${(v*100).toFixed(1)}%`).join(' Â· ');$(`#result`).innerHTML=`<b>MobileViT prediction: ${d.prediction}</b><br><small>Confidence ${(d.confidence*100).toFixed(1)}% Â· ${probs}</small>`;log(`Inference completed: ${d.prediction} (${(d.confidence*100).toFixed(1)}%).`,'success')}
function drawAttention(source){const c=$(`#attentionCanvas`),ctx=c.getContext('2d'),map=new Image();map.onload=()=>{c.width=map.width;c.height=map.height;ctx.drawImage(map,0,0);c.classList.remove('hidden');$(`#attentionPlaceholder`).classList.add('hidden')};map.src=source}
$(`#hospitalSlider`).oninput=renderNetwork;$(`#trainBtn`).onclick=train;$(`#resetBtn`).onclick=reset;$(`#fileInput`).onchange=e=>choose(e.target.files[0]);$(`#diagnoseBtn`).onclick=diagnose;$(`#clearBtn`).onclick=()=>{file=null;$(`#preview`).removeAttribute('src');$(`#inputPlaceholder`).classList.remove('hidden');$(`#result`).classList.add('hidden');$(`#diagnoseBtn`).disabled=true};const dz=$(`#dropzone`);dz.ondragover=e=>e.preventDefault();dz.ondrop=e=>{e.preventDefault();choose(e.dataTransfer.files[0])};renderNetwork();log('System environment ready.');

